name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependancies
        run: npm ci --include=dev
      - name: Build app
        run: npm run build
      - name: Start app
        run: npm run dev
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
      - name: Run Cypress Tests (headless)
        uses: cypress-io/github-action@v6
        with:
          start: npm run cypress:run
