name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./web/golfcaddy2.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependancies
        run: npm ci --include=dev
      - name: Build app
        run: npm run build
      - name: Cypress
        run: npx cypress run
        
       
        
          
           
      
