name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Switch directory
        run: cd web/golfcaddy2.0
      - name: Dependancies
        run: npm ci --include=dev
      - name: Start app
        run: npm run dev
      - name: Cypress
        run: npx cypress run
      
