name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Switch directory
        run: cd web
      - name: Switch directory 2
        run: cd web
      - name: Check directory
        run: ls
      - name: Dependancies
        run: npm ci --include=dev
      - name: Cypress
        run: npx cypress run
      
