name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run App and tests
        working-directory: ./web/golfcaddy2.0
      - name: Dependancies
        run: npm ci --include=dev
      - name: Cypress
        run: npx cypress run
      
